source "https://rubygems.org/"

gem "iruby", github: "SciRuby/iruby"
gem "cztop"
gem "rroonga", path: "/home/kou/work/ruby/rroonga"
gem "rroonga-iruby", path: "/home/kou/work/ruby/rroonga-iruby"
gem "pry"
gem "nyaplot"
