---
id: nagoya-rubykaigi-03
base_name: apache-arrow-gi-based-ruby-bindings
tags:
- rabbit
- arrow
- gobject-introspection
- ruby
- bindings
presentation_date: 2017-02-11
version: 2017.2.11.0
licenses:
- CC-BY-SA-4.0
- Apache-2.0
- CC-BY-3.0
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: 須藤功平
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: 
